// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

public type OpenAI\.ContextManagementParam record {
    string 'type;
    int? compact_threshold?;
};

public type OpenAI\.ConversationReference record {
    string id;
};

public type OpenAI\.OutputItemType string|"output_message"|"file_search_call"|"function_call"|"function_call_output"|"web_search_call"|"computer_call"|"computer_call_output"|"reasoning"|"tool_search_call"|"tool_search_output"|"compaction"|"image_generation_call"|"code_interpreter_call"|"local_shell_call"|"local_shell_call_output"|"shell_call"|"shell_call_output"|"apply_patch_call"|"apply_patch_call_output"|"mcp_call"|"mcp_list_tools"|"mcp_approval_request"|"mcp_approval_response"|"custom_tool_call"|"custom_tool_call_output"|"tool_approval_request";

public type OpenAI\.InputParam string|OpenAI\.InputItem[];

public type OpenAI\.ToolChoiceOptions "none"|"auto"|"required";

public type OpenAI\.ResponseUsage record {
    int input_tokens;
    OpenAI\.ResponseUsageInputTokensDetails input_tokens_details;
    int output_tokens;
    OpenAI\.ResponseUsageOutputTokensDetails output_tokens_details;
    int total_tokens;
};

public type OpenAI\.ItemResource record {
    OpenAI\.ItemResourceType 'type;
};

public type OpenAI\.ResponseUsageOutputTokensDetails record {
    int reasoning_tokens;
};

public type AzureAIFoundryModelsApiVersion "v1"|"preview";

# If available, the citation details describing the associated license and its location.
public type AzureContentFilterResultsForResponsesAPI_protected_material_code_citation record {
    # The name or identifier of the license associated with the detection.
    string license?;
    # The URL associated with the license.
    string URL?;
};

public type OpenAI\.ToolsArray OpenAI\.Tool[];

public type AzureContentFilterResultOffsets record {
    int:Signed32 start_offset;
    int:Signed32 end_offset;
    int:Signed32 check_offset;
};

# Represents the Queries record for the operation: cancelResponse
public type CancelResponseQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
};

public type OpenAI\.IncludeEnum string|"file_search_call.results"|"web_search_call.results"|"web_search_call.action.sources"|"message.input_image.image_url"|"computer_call_output.output.image_url"|"code_interpreter_call.outputs"|"reasoning.encrypted_content"|"message.output_text.logprobs";

public type OpenAI\.ResponseIncompleteDetails record {
    "max_output_tokens"|"content_filter" reason?;
};

public type OpenAI\.OutputItem record {
    OpenAI\.OutputItemType 'type;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Provides Auth configurations needed when communicating with a remote HTTP endpoint.
    http:BearerTokenConfig|ApiKeysConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type AzureContentFilterCompletionTextSpanDetectionResult record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
    # Detailed information about the detected completion text spans.
    AzureContentFilterCompletionTextSpan[] details;
};

# Represents the Queries record for the operation: createResponse
public type CreateResponseQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
};

public type AzureContentFilterCustomTopicResult_details record {
    # A value indicating whether the topic is detected.
    boolean detected;
    # The ID of the custom topic evaluated.
    string id;
};

public type OpenAI\.ResponseTextParam record {
    OpenAI\.TextResponseFormatConfiguration format?;
    OpenAI\.Verbosity? verbosity?;
};

public type OpenAI\.TextResponseFormatConfigurationType string|"text"|"json_schema"|"json_object";

# A labeled content filter result item that indicates whether the content was detected and whether the content was
# filtered.
public type AzureContentFilterDetectionResult record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
};

public type OpenAI\.ResponseUsageInputTokensDetails record {
    int cached_tokens;
};

public type inline_response_200_1 record {
    "response.deleted" 'object;
    string id;
    true deleted;
};

public type AzureContentFilterBlocklistResult_details record {
    # A value indicating whether the blocklist produced a filtering action.
    boolean filtered;
    # The ID of the custom blocklist evaluated.
    string id;
};

public type OpenAI\.ResponseError record {
    OpenAI\.ResponseErrorCode code;
    string message;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    string api\-key;
    string authorization;
|};

public type OpenAI\.TextResponseFormatConfiguration record {
    OpenAI\.TextResponseFormatConfigurationType 'type;
};

public type OpenAI\.ResponseStreamOptions record {
    boolean include_obfuscation?;
};

# Represents the Queries record for the operation: deleteResponse
public type DeleteResponseQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
};

# A collection of true/false filtering results for configured custom topics.
public type AzureContentFilterCustomTopicResult record {
    # A value indicating whether any of the detailed topics resulted in a filtering action.
    boolean filtered;
    # The pairs of individual topic IDs and whether they are detected.
    AzureContentFilterCustomTopicResult_details[] details?;
};

public type AzureContentFilterForResponsesAPI record {
    # Indicate if the response is blocked.
    boolean blocked;
    # The name of the source type of the message.
    string source_type;
    # A content filter result for a single response item produced by a generative AI system.
    AzureContentFilterResultsForResponsesAPI content_filter_results;
    AzureContentFilterResultOffsets content_filter_offsets;
    # The ID of the tool call associated with this content filter result, if applicable.
    string tool_call_id?;
};

# Represents the Queries record for the operation: listInputItems
public type ListInputItemsQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
    # A cursor for use in pagination. `before` is an object ID that defines your place in the list.
    # For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
    # subsequent call can include before=obj_foo in order to fetch the previous page of the list.
    string before?;
    # A limit on the number of objects to be returned. Limit can range between 1 and 100, and the
    # default is 20.
    int:Signed32 'limit = 20;
    # A cursor for use in pagination. `after` is an object ID that defines your place in the list.
    # For instance, if you make a list request and receive 100 objects, ending with obj_foo, your
    # subsequent call can include after=obj_foo in order to fetch the next page of the list.
    string after?;
    # Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and`desc`
    # for descending order.
    "asc"|"desc" 'order?;
};

public type OpenAI\.ResponsePromptVariables record {
};

# Represents the Queries record for the operation: getResponse
public type GetResponseQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
    # If set to true, the model response data will be streamed to the client as it is generated using server-sent events.
    boolean 'stream?;
    # The sequence number of the event after which to start streaming.
    int:Signed32 starting_after?;
    # Additional fields to include in the response. See the include parameter for Response creation above for more information.
    OpenAI\.IncludeEnum[] include\[\] = [];
    # When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an `obfuscation` field on streaming delta events to normalize payload sizes as a mitigation to certain side-channel attacks. These obfuscation fields are included by default, but add a small amount of overhead to the data stream. You can set `include_obfuscation` to false to optimize for bandwidth if you trust the network links between your application and the OpenAI API.
    boolean include_obfuscation = true;
};

public type OpenAI\.ResponseErrorCode "server_error"|"rate_limit_exceeded"|"invalid_prompt"|"vector_store_timeout"|"invalid_image"|"invalid_image_format"|"invalid_base64_image"|"invalid_image_url"|"image_too_large"|"image_too_small"|"image_parse_error"|"image_content_policy_violation"|"invalid_image_mode"|"image_file_too_large"|"unsupported_image_media_type"|"empty_image_file"|"failed_to_download_image"|"image_file_not_found";

# A detection result that describes a match against licensed code or other protected source material.
public type AzureContentFilterResultsForResponsesAPI_protected_material_code record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
    # If available, the citation details describing the associated license and its location.
    AzureContentFilterResultsForResponsesAPI_protected_material_code_citation citation?;
};

public type OpenAI\.Verbosity "low"|"medium"|"high"?;

# If present, details about an error that prevented content filtering from completing its evaluation.
public type AzureContentFilterResultsForResponsesAPI_error record {
    # A distinct, machine-readable code associated with the error.
    int:Signed32 code;
    # A human-readable message associated with the error.
    string message;
};

# A representation of a span of completion text as used by Azure OpenAI content filter results.
public type AzureContentFilterCompletionTextSpan record {
    # Offset of the UTF32 code point which begins the span.
    int:Signed32 completion_start_offset;
    # Offset of the first UTF32 code point which is excluded from the span. This field is always equal to completion_start_offset for empty spans. This field is always larger than completion_start_offset for non-empty spans.
    int:Signed32 completion_end_offset;
};

public type inline_response_200 record {
    # Set of 16 key-value pairs that can be attached to an object. This can be
    # useful for storing additional information about the object in a structured
    # format, and querying for objects via API or the dashboard.
    # Keys are strings with a maximum length of 64 characters. Values are strings
    # with a maximum length of 512 characters.
    OpenAI\.Metadata metadata?;
    int? top_logprobs?;
    decimal? temperature = 1;
    decimal? top_p = 1;
    # This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.
    #   A stable identifier for your end-users.
    #   Used to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    # 
    # # Deprecated
    @deprecated
    string user?;
    # A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
    #   The IDs should be a string that uniquely identifies each user, with a maximum length of 64 characters. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    @constraint:String {maxLength: 64}
    string safety_identifier?;
    # Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](/docs/guides/prompt-caching).
    string prompt_cache_key?;
    "in_memory"|"24h"? prompt_cache_retention?;
    string? previous_response_id?;
    # Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI
    #   offers a wide range of models with different capabilities, performance
    #   characteristics, and price points. Refer to the [model guide](/docs/models)
    #   to browse and compare available models.
    string model?;
    # **gpt-5 and o-series models only**
    # Configuration options for
    # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    OpenAI\.Reasoning reasoning?;
    boolean? background?;
    int? max_tool_calls?;
    # Configuration options for a text response from the model. Can be plain
    # text or structured JSON data. Learn more:
    # - [Text inputs and outputs](/docs/guides/text)
    # - [Structured Outputs](/docs/guides/structured-outputs)
    OpenAI\.ResponseTextParam text?;
    # An array of tools the model may call while generating a response. You
    # can specify which tool to use by setting the `tool_choice` parameter.
    # We support the following categories of tools:
    # - **Built-in tools**: Tools that are provided by OpenAI that extend the
    # model's capabilities, like [web search](/docs/guides/tools-web-search)
    # or [file search](/docs/guides/tools-file-search). Learn more about
    # [built-in tools](/docs/guides/tools).
    # - **MCP Tools**: Integrations with third-party systems via custom MCP servers
    # or predefined connectors such as Google Drive and SharePoint. Learn more about
    # [MCP Tools](/docs/guides/tools-connectors-mcp).
    # - **Function calls (custom tools)**: Functions that are defined by you,
    # enabling the model to call your own code with strongly typed arguments
    # and outputs. Learn more about
    # [function calling](/docs/guides/function-calling). You can also use
    # custom tools to call your own code.
    OpenAI\.ToolsArray tools?;
    OpenAI\.ToolChoiceOptions|OpenAI\.ToolChoiceParam tool_choice?;
    # Reference to a prompt template and its variables.
    # [Learn more](/docs/guides/text?api-mode=responses#reusable-prompts).
    OpenAI\.Prompt prompt?;
    "auto"|"disabled"? truncation = "disabled";
    # Unique identifier for this Response.
    string id;
    # The object type of this resource - always set to `response`.
    "response" 'object;
    # The status of the response generation. One of `completed`, `failed`,
    #   `in_progress`, `cancelled`, `queued`, or `incomplete`.
    "completed"|"failed"|"in_progress"|"cancelled"|"queued"|"incomplete" status?;
    # Unix timestamp (in seconds) of when this Response was created.
    int created_at;
    string? completed_at?;
    # An error object returned when the model fails to generate a Response.
    OpenAI\.ResponseError 'error;
    OpenAI\.ResponseIncompleteDetails incomplete_details;
    # An array of content items generated by the model.
    #   - The length and order of items in the `output` array is dependent
    #   on the model's response.
    #   - Rather than accessing the first item in the `output` array and
    #   assuming it's an `assistant` message with the content generated by
    #   the model, you might consider using the `output_text` property where
    #   supported in SDKs.
    OpenAI\.OutputItem[] output;
    string|OpenAI\.InputItem[]? instructions;
    string? output_text?;
    # Represents token usage details including input tokens, output tokens,
    # a breakdown of output tokens, and the total tokens used.
    OpenAI\.ResponseUsage usage?;
    # Whether to allow the model to run tool calls in parallel.
    boolean parallel_tool_calls = true;
    # The conversation that this response belonged to. Input items and output items from this response were automatically added to this conversation.
    OpenAI\.ConversationReference conversation?;
    int? max_output_tokens?;
    # The content filter results from RAI.
    AzureContentFilterForResponsesAPI[] content_filters?;
};

public type OpenAI\.ConversationParam string|OpenAI\.ConversationParam\-2;

public type AzureContentFilterResultsForResponsesAPI record {
    # A content filter category for language related to anatomical organs and genitals, romantic relationships, acts
    # portrayed in erotic or affectionate terms, pregnancy, physical sexual acts, including those portrayed as an
    # assault or a forced sexual violent act against one's will, prostitution, pornography, and abuse.
    AzureContentFilterSeverityResult sexual?;
    # A content filter category that can refer to any content that attacks or uses pejorative or discriminatory
    # language with reference to a person or identity group based on certain differentiating attributes of these groups
    # including but not limited to race, ethnicity, nationality, gender identity and expression, sexual orientation,
    # religion, immigration status, ability status, personal appearance, and body size.
    AzureContentFilterSeverityResult hate?;
    # A content filter category for language related to physical actions intended to hurt, injure, damage, or kill
    # someone or something; describes weapons, guns and related entities, such as manufactures, associations,
    # legislation, and so on.
    AzureContentFilterSeverityResult violence?;
    # A content filter category that describes language related to physical actions intended to purposely hurt, injure,
    # damage one's body or kill oneself.
    AzureContentFilterSeverityResult self_harm?;
    # A detection result that identifies whether crude, vulgar, or otherwise objection language is present in the
    # content.
    AzureContentFilterDetectionResult profanity?;
    # A collection of binary filtering outcomes for configured custom blocklists.
    AzureContentFilterBlocklistResult custom_blocklists?;
    # A collection of binary filtering outcomes for configured custom topics.
    AzureContentFilterCustomTopicResult custom_topics?;
    # If present, details about an error that prevented content filtering from completing its evaluation.
    AzureContentFilterResultsForResponsesAPI_error 'error?;
    # A detection result that describes user prompt injection attacks, where malicious users deliberately exploit
    # system vulnerabilities to elicit unauthorized behavior from the LLM. This could lead to inappropriate content
    # generation or violations of system-imposed restrictions.
    AzureContentFilterDetectionResult jailbreak;
    # A detection result that indicates if the execution flow still sticks the plan.
    AzureContentFilterDetectionResult task_adherence;
    # A detection result that describes a match against text protected under copyright or other status.
    AzureContentFilterDetectionResult protected_material_text?;
    # A detection result that describes a match against licensed code or other protected source material.
    AzureContentFilterResultsForResponsesAPI_protected_material_code protected_material_code?;
    AzureContentFilterCompletionTextSpanDetectionResult ungrounded_material?;
    # A detection result that describes matches against Personal Identifiable Information with configurable subcategories.
    AzureContentFilterPersonallyIdentifiableInformationResult personally_identifiable_information?;
    # A detection result that describes attacks on systems powered by Generative AI models that can happen every time
    # an application processes information that wasn’t directly authored by either the developer of the application or
    # the user.
    AzureContentFilterDetectionResult indirect_attack?;
};

public type OpenAI\.ToolChoiceParam record {
    OpenAI\.ToolChoiceParamType 'type;
};

public type OpenAI\.Tool record {
    OpenAI\.ToolType 'type;
};

public type OpenAI\.ReasoningEffort "none"|"minimal"|"low"|"medium"|"high"|"xhigh"?;

# A content filter detection result for Personally Identifiable Information that includes harm extensions.
public type AzureContentFilterPersonallyIdentifiableInformationResult AzureContentFilterDetectionResult;

public type OpenAI\.ItemResourceType string|"message"|"output_message"|"file_search_call"|"computer_call"|"computer_call_output"|"web_search_call"|"function_call"|"function_call_output"|"tool_search_call"|"tool_search_output"|"reasoning"|"compaction"|"image_generation_call"|"code_interpreter_call"|"local_shell_call"|"local_shell_call_output"|"shell_call"|"shell_call_output"|"apply_patch_call"|"apply_patch_call_output"|"mcp_list_tools"|"mcp_approval_request"|"mcp_approval_response"|"mcp_call"|"custom_tool_call"|"custom_tool_call_output";

public type OpenAI\.InputItemType string|"message"|"output_message"|"file_search_call"|"computer_call"|"computer_call_output"|"web_search_call"|"function_call"|"function_call_output"|"tool_search_call"|"tool_search_output"|"reasoning"|"compaction"|"image_generation_call"|"code_interpreter_call"|"local_shell_call"|"local_shell_call_output"|"shell_call"|"shell_call_output"|"apply_patch_call"|"apply_patch_call_output"|"mcp_list_tools"|"mcp_approval_request"|"mcp_approval_response"|"mcp_call"|"custom_tool_call_output"|"custom_tool_call"|"item_reference"|"tool_approval_response";

public type OpenAI\.Metadata record {
};

# A labeled content filter result item that indicates whether the content was filtered and what the qualitative
# severity level of the content was, as evaluated against content filter configuration for the category.
public type AzureContentFilterSeverityResult record {
    # Whether the content severity resulted in a content filtering action.
    boolean filtered;
    # The labeled severity of the content.
    "safe"|"low"|"medium"|"high" severity;
};

public type OpenAI\.InputItem record {
    OpenAI\.InputItemType 'type;
};

public type OpenAI\.ResponseItemList record {
    "list" 'object;
    OpenAI\.ItemResource[] data;
    boolean has_more;
    string first_id;
    string last_id;
};

public type OpenAI\.Reasoning record {
    OpenAI\.ReasoningEffort? effort?;
    "auto"|"concise"|"detailed"? summary?;
    "auto"|"concise"|"detailed"? generate_summary?;
};

public type OpenAI\.CreateResponse record {
    OpenAI\.Metadata metadata?;
    int? top_logprobs?;
    decimal? temperature = 1;
    decimal? top_p = 1;
    string user?;
    string safety_identifier?;
    string prompt_cache_key?;
    "in_memory"|"24h"? prompt_cache_retention?;
    string? previous_response_id?;
    string model?;
    OpenAI\.Reasoning reasoning?;
    boolean? background?;
    int? max_tool_calls?;
    OpenAI\.ResponseTextParam text?;
    OpenAI\.ToolsArray tools?;
    OpenAI\.ToolChoiceOptions|OpenAI\.ToolChoiceParam tool_choice?;
    OpenAI\.Prompt prompt?;
    "auto"|"disabled"? truncation = "disabled";
    OpenAI\.InputParam input?;
    OpenAI\.IncludeEnum[]? include?;
    boolean? parallel_tool_calls = true;
    boolean? store = true;
    string? instructions?;
    boolean? 'stream?;
    OpenAI\.ResponseStreamOptions stream_options?;
    OpenAI\.ConversationParam conversation?;
    OpenAI\.ContextManagementParam[]? context_management?;
    int? max_output_tokens?;
};

public type OpenAI\.ToolChoiceParamType string|"allowed_tools"|"function"|"mcp"|"custom"|"apply_patch"|"shell"|"file_search"|"web_search_preview"|"computer_use_preview"|"web_search_preview_2025_03_11"|"image_generation"|"code_interpreter"|"computer"|"computer_use";

# A collection of true/false filtering results for configured custom blocklists.
public type AzureContentFilterBlocklistResult record {
    # A value indicating whether any of the detailed blocklists resulted in a filtering action.
    boolean filtered;
    # The pairs of individual blocklist IDs and whether they resulted in a filtering action.
    AzureContentFilterBlocklistResult_details[] details?;
};

public type OpenAI\.Prompt record {
    string id;
    string? version?;
    OpenAI\.ResponsePromptVariables variables?;
};

public type OpenAI\.ToolType string|"function"|"file_search"|"computer"|"computer_use_preview"|"web_search"|"mcp"|"code_interpreter"|"image_generation"|"local_shell"|"shell"|"custom"|"namespace"|"tool_search"|"web_search_preview"|"apply_patch";

public type OpenAI\.ConversationParam\-2 record {
    string id;
};
